"""remove field <название_поля>

Revision ID: f318f4ef5ae2
Revises: 956a74a7b0ec
Create Date: 2025-06-24 18:20:07.158698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f318f4ef5ae2'
down_revision: Union[str, Sequence[str], None] = '956a74a7b0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
