"""Add created_at and is_public to Note

Revision ID: 002_add_note_fields
Revises: 001_initial
Create Date: 2025-01-13 12:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_add_note_fields'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('created_at', sa.String(), nullable=True))
    op.add_column('note', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'is_public')
    op.drop_column('note', 'created_at')
    # ### end Alembic commands ###
