"""deleted field

Revision ID: 5860d4f9027a
Revises: e1cc540bee1f
Create Date: 2025-06-30 09:38:05.992323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5860d4f9027a'
down_revision: Union[str, Sequence[str], None] = 'e1cc540bee1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
